import = [
  "~/.config/alacritty/themes/alacritty-theme/themes/blood_moon.toml"
]

[window]
decorations = "None"
opacity = 0.85
startup_mode = "Maximized"
padding = { x = 0, y = 10 }

[font]
normal = { family = "FiraCode Nerd Font", style = "Bold" }
size = 14.0

[colors]
primary = { foreground = "#FFFFFF", background = "#000000" }

[shell]
program = "/usr/bin/zsh"

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]
